SIM = verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/second_largest.v
COCOTB_TOPLEVEL = model
COCOTB_TEST_MODULES = second_largest_test
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim
